create table authors
(
    id            bigserial primary key,
    created_at    timestamp,
    date_of_birth date,
    first_name    varchar(255),
    last_name     varchar(255),
    patronymic    varchar(255)
);

create table publishers
(
    id              bigserial primary key,
    publishers_name varchar(255) not null
);

create table genres
(
    id         bigserial primary key,
    genre_name varchar(255) not null
);

create table books
(
    id            bigserial
        primary key,
    book_image    varchar(255),
    book_name     varchar(255),
    num_of_page   integer,
    price         double precision,
    book_quantity integer,
    year_of_issue integer,
    publisher_id  bigint references publishers (id)
);

create table author_book_table
(
    book_id   bigint not null,
    constraint fk_book
        foreign key (book_id)
            references books (id),
    author_id bigint not null,
    constraint fk_author
        foreign key (author_id)
            references authors (id)
);

create table book_genre_table
(
    book_id  bigint not null,
    constraint fk_books
        foreign key (book_id)
            references books (id),
    genre_id bigint not null,
    constraint fk_genres
        foreign key (genre_id)
            references genres (id)
);

create table users
(
    id         bigserial
        primary key,
    is_blocked boolean      not null,
    password   varchar(255) not null,
    user_role  varchar(255) not null,
    user_name  varchar(255) not null,
    unique (user_name)
);

create table orders
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp,
    order_status varchar(255),
    user_id      bigint,
    constraint fk_user
        foreign key (user_id)
            references users (id)
);

create table order_book_table
(
    book_id       bigint not null,
    constraint fk_book
        foreign key (book_id)
            references books (id),
    order_id      bigint not null,
    constraint fk_order
        foreign key (order_id)
            references orders (id),
    book_quantity bigint,
    primary key (book_id, order_id)
);


create table cart_table
(
    id           bigint generated by default as identity
        primary key,
    quantity bigint,
    book_id      bigint,
    constraint fk_book
        foreign key (book_id)
            references books (id),
    user_id      bigint,
    constraint fk_user
        foreign key (user_id)
            references users (id)
);










